version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rolecontainer
    restart: always
    environment:
      POSTGRES_USER: nasir
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springboot-app:
    build: .
    container_name: roleapp
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/TechMart
      SPRING_DATASOURCE_USERNAME: nasir
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8061:8061"

volumes:
  pgdata: